import Kendaraan from "./kendaraan";

const DataStations = [
  {
    title: "Juanda",
    distance: "1 km",
    status: "Lancar",
    type: "stasiun",
    armada: "commuterline",
    kendaraan: Kendaraan["commuterline"],
  },
  {
    title: "Juanda",
    distance: "1 km",
    status: "Lancar",
    type: "halte",
    armada: "transjakarta",
    kendaraan: Kendaraan["transjakarta"],
  },
  {
    title: "Juanda",
    distance: "1 km",
    status: "Lancar",
    type: "halte",
    armada: "jaklingko",
    kendaraan: Kendaraan["jaklingko"],
  },
  {
    title: "Mangga Besar",
    distance: "3 km",
    status: "Padat",
    type: "stasiun",
    armada: "commuterline",
    kendaraan: Kendaraan["commuterline"],
  },
  {
    title: "Mangga Besar",
    distance: "3 km",
    status: "Padat",
    type: "halte",
    armada: "transjakarta",
    kendaraan: Kendaraan["transjakarta"],
  },
  {
    title: "Mangga Besar",
    distance: "3 km",
    status: "Padat",
    type: "halte",
    armada: "jaklingko",
    kendaraan: Kendaraan["jaklingko"],
  },
  {
    title: "Cikini",
    distance: "2 km",
    status: "Lancar",
    type: "stasiun",
    armada: "commuterline",
    kendaraan: Kendaraan["commuterline"],
  },
  {
    title: "Cikini",
    distance: "2 km",
    status: "Lancar",
    type: "stasiun",
    armada: "commuterline",
    kendaraan: Kendaraan["commuterline"],
  },
  {
    title: "Gondangdia",
    distance: "4 km",
    status: "Padat",
    type: "stasiun",
    armada: "commuterline",
    kendaraan: Kendaraan["commuterline"],
  },
  {
    title: "Tanah Abang",
    distance: "7 km",
    status: "Padat",
    type: "stasiun",
    armada: "commuterline",
    kendaraan: Kendaraan["commuterline"],
  },
  {
    title: "Pasar Baru",
    distance: "3 km",
    status: "Padat",
    type: "halte",
    armada: "transjakarta",
    kendaraan: Kendaraan["transjakarta"],
  },
  {
    title: "Bundaran HI",
    distance: "4 km",
    status: "Padat",
    type: "stasiun",
    armada: "mrt",
    kendaraan: Kendaraan["mrt"],
  },
  {
    title: "Kota",
    distance: "4 km",
    status: "Padat",
    type: "stasiun",
    armada: "commuterline",
    kendaraan: Kendaraan["commuterline"],
  },
  {
    title: "Depok",
    distance: "16 km",
    status: "Lancar",
    type: "stasiun",
    armada: "commuterline",
    kendaraan: Kendaraan["commuterline"],
  },
  {
    title: "BNI Sudirman",
    distance: "4 km",
    status: "Padat",
    type: "stasiun",
    armada: "mrt",
    kendaraan: Kendaraan["mrt"],
  },
  {
    title: "Ciracas",
    distance: "7 km",
    status: "Padat",
    type: "stasiun",
    armada: "lrt",
    kendaraan: Kendaraan["lrt"],
  },
  {
    title: "Cawang",
    distance: "4 km",
    status: "Lancar",
    type: "stasiun",
    armada: "lrt",
    kendaraan: Kendaraan["lrt"],
  },
  {
    title: "Blok M BCA",
    distance: "4 km",
    status: "Padat",
    type: "stasiun",
    armada: "mrt",
    kendaraan: Kendaraan["mrt"],
  },
  {
    title: "Pasar Minggu",
    distance: "1 km",
    status: "Lancar",
    type: "stasiun",
    armada: "commuterline",
    kendaraan: Kendaraan["commuterline"],
  },
  {
    title: "Klender",
    distance: "12 km",
    status: "Padat",
    type: "stasiun",
    armada: "commuterline",
    kendaraan: Kendaraan["commuterline"],
  },
  {
    title: "Kebon Bawang",
    distance: "13 km",
    status: "lancar",
    type: "halte",
    armada: "transjakarta",
    kendaraan: Kendaraan["transjakarta"],
  },
  {
    title: "Cikunir",
    distance: "7 km",
    status: "Padat",
    type: "stasiun",
    armada: "lrt",
    kendaraan: Kendaraan["lrt"],
  },
  {
    title: "Indomaret Fatmawati",
    distance: "4 km",
    status: "lancar",
    type: "stasiun",
    armada: "mrt",
    kendaraan: Kendaraan["mrt"],
  },
];
export default DataStations;
